### PR TITLE
fix(qbx_hudcomponents): Allow weapon scopes to be used

### LINKED ISSUE #119: [Suggestion/issue] Check for scoped weapons in hide hud components
### Summary

hidehudcomponents doesn't consider that some weapons have scope reticules

### Reproduction

This is an issue with how hidehudcomponents is coded.

https://github.com/Qbox-project/qbx_smallresources/blob/a549aed7d7df3dd91b9f8ceb6e0c09b865dcd334/qbx_hudcomponents/client.lua#L40

For example, in this fix that went stale in qb-smallresources:

https://github.com/qbcore-framework/qb-smallresources/pull/326/files#diff-e7bc7e42f01f31f2c93fcc43ba761b7a547f8cee620a4d596c2fdb5dc175feff

Detection is done by doing:

` 
-- Check for sniper rifle
        local currentWeapon = GetSelectedPedWeapon(PlayerPedId())
        if currentWeapon == GetHashKey("WEAPON_SNIPERRIFLE") or currentWeapon == GetHashKey("WEAPON_MARKSMANRIFLE") or currentWeapon == GetHashKey("WEAPON_MARKSMANRIFLE_MK2") or currentWeapon == GetHashKey("WEAPON_HEAVYSNIPER") then
            ShowHudComponentThisFrame(14)
        else
            HideHudComponentThisFrame(14)
        end
 `
 
 This works, but there's likely a more elegant solution that could go in a config or something, to account for custom weapons, future additions by rockstar.

### Expected behavior

Snipers/scoped weapons display their reticle, even when reticles are disabled

### Actual behavior

Hides sniper reticle

### Additional context

While many people disable the crosshair for many reasons (RP, replacing it with their own server's crosshair, etc) this creates a problem for scoped weapons, as the overlay is actually the same type of reticle used in third person, just a different style.

### Current Version

N/A

### Custom Resources

N/A

### PR DESCRIPTION
**Pull request by citRaTTV**
## Description

Allows weapon scopes to be used by using IsFirstPersonAimCamActive(). Closes https://github.com/Qbox-project/qbx_smallresources/issues/119

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

File: qbx_hudcomponents/client.lua [hunk 1]
```diff
@@ -4,20 +4,31 @@ local disableControls = config.disable.controls
...
-        
         Wait(0)
     end
 end)
 
+lib.onCache('weapon', function(weapon)
+    if not weapon then return end
+    CreateThread(function()
+        while cache.weapon ~= weapon do Wait(1) end -- Wait for cache.weapon to update
+        while cache.weapon == weapon do
```
Comment (BerkieBb) [inline qbx_hudcomponents/client.lua]: For style, add a space above this line as both loops serve different purposes

File: qbx_hudcomponents/client.lua [hunk 2]
```diff
@@ -4,20 +4,31 @@ local disableControls = config.disable.controls
...
             DisableControlAction(2, disableControls[i], true)
         end
-        
         Wait(0)
     end
 end)
 
+lib.onCache('weapon', function(weapon)
+    if not weapon then return end
+    CreateThread(function()
```
Comment (BerkieBb) [inline qbx_hudcomponents/client.lua]: For style, add a space between the if statement and the thread as they are separate from each other.

Comment (citRaTTV) [reply qbx_hudcomponents/client.lua]: Done!

File: qbx_hudcomponents/client.lua (hunk 1 above)
Comment (citRaTTV) [reply qbx_hudcomponents/client.lua]: Done!

**Review by ihyajb — APPROVED** [review]
